#!/bin/bash

#SBATCH --job-name=vlm
#SBATCH --gres=gpu:rtx6000:1
#SBATCH --time=48:00:00
#SBATCH -c 8
#SBATCH -p gpu
#SBATCH --mem=80G
#SBATCH --output=/home/jinwoongjung/MTGS/scripts/logs/vlm_%j.out
#SBATCH --error=/home/jinwoongjung/MTGS/scripts/logs/vlm_%j.err

set -e

# Slurm keeps stdout/stderr separate: model loading (Transformers/PEFT/W&B setup) and
# real errors land in .err, while our own train/val tqdm bars and the epoch/result
# reports (printed via Python's stdout) land in .out.

# set arguments
CONFIG=${CONFIG:-mtgs/config/config_vlm.yaml}
CACHE="/home/jinwoongjung/MTGS/data/graph_cache"

# A profile chooses the dataset subset. Leave MANIFEST_PROFILE empty to read
# data.profile from CONFIG.
MANIFEST_PROFILE=""
MANIFEST_ROOT=""

RESUME=""

# This script defaults to train/validation only. Run held-out test evaluation
# explicitly through eval_vlm.sh after selecting the final checkpoint.
TEST_EVAL=1
TEST_BATCH_SIZE=0
TEST_NUM_WORKERS=-1
TEST_OUT=""
TEST_NAME=""

source /opt/miniconda3/etc/profile.d/conda.sh
conda activate mtgs
export PYTHONNOUSERSITE=1
export XFORMERS_DISABLED=1

if [ "$(basename "$SLURM_SUBMIT_DIR")" = "scripts" ]; then
    cd "$(dirname "$SLURM_SUBMIT_DIR")"
else
    cd "$SLURM_SUBMIT_DIR"
fi

mkdir -p scripts/logs
if [ -z "$MANIFEST_PROFILE" ]; then
    MANIFEST_PROFILE=$(python - "$CONFIG" <<'PYCFG'
import sys
from omegaconf import OmegaConf
print(OmegaConf.load(sys.argv[1]).get("data", {}).get("profile", "full"))
PYCFG
)
fi
MANIFEST_ROOT=${MANIFEST_ROOT:-$CACHE/manifests/$MANIFEST_PROFILE}
if [ ! -f "$MANIFEST_ROOT/manifest_train.jsonl" ] || [ ! -f "$MANIFEST_ROOT/manifest_val.jsonl" ]; then
    echo "Missing train/val manifests under MANIFEST_ROOT=$MANIFEST_ROOT" >&2
    exit 2
fi

# Confidence-gated routing can train on the VLM-routed remainder only, or on the full
# train population as auxiliary data. Validation always remains full: training.py routes
# it internally, mirroring eval_vlm.sh's held-out-test behaviour.
read -r ROUTING_USE ROUTING_THR ROUTING_TRAIN_POPULATION < <(python - "$CONFIG" <<'PYCFG'
import sys
from omegaconf import OmegaConf
r = OmegaConf.load(sys.argv[1]).get("routing", {})
population = str(r.get("train_population", "low_confidence")).lower().replace("-", "_")
population = {"low_conf": "low_confidence"}.get(population, population)
if population not in {"low_confidence", "full"}:
    raise SystemExit(
        "routing.train_population must be 'low_confidence' or 'full', got " + repr(population)
    )
print(bool(r.get("use", False)), r.get("threshold", 0.8), population)
PYCFG
)
TRAIN_MANIFEST="$MANIFEST_ROOT/manifest_train.jsonl"
VAL_MANIFEST="$MANIFEST_ROOT/manifest_val.jsonl"
if [ "$ROUTING_USE" = "True" ] && [ "$ROUTING_TRAIN_POPULATION" = "low_confidence" ]; then
    LOWCONF_ROOT="$CACHE/manifests/${MANIFEST_PROFILE}_lowconf${ROUTING_THR}"
    mkdir -p "$LOWCONF_ROOT"
    python -m vlm.cache.filter_lowconf_manifest \
        --manifest "$TRAIN_MANIFEST" \
        --graph_feats "$CACHE/vlmgraph_train.pt" \
        --out "$LOWCONF_ROOT/manifest_train.jsonl" \
        --report "$LOWCONF_ROOT/report_train.json" \
        --threshold "$ROUTING_THR"
    TRAIN_MANIFEST="$LOWCONF_ROOT/manifest_train.jsonl"
    echo "[vlm] routing ON (threshold=$ROUTING_THR): train_population=low_confidence; val stays full"
elif [ "$ROUTING_USE" = "True" ]; then
    echo "[vlm] routing ON (threshold=$ROUTING_THR): train_population=full; val stays full"
fi
echo "[vlm] manifest_profile=$MANIFEST_PROFILE train_manifest=$TRAIN_MANIFEST val_manifest=$VAL_MANIFEST"
RESUME_ARGS=()
[ -n "$RESUME" ] && RESUME_ARGS=(--resume "$RESUME")

# Resolve RUN_DIR now, before training starts, and freeze it. Training can run
# for hours; if $CONFIG is edited on disk in the meantime (e.g. to queue the
# next experiment), a post-hoc re-read here would silently point the test
# stage at the wrong run directory. Reading it once up front makes the test
# stage immune to later edits of the same config file.
RUN_DIR=$(python - "$CONFIG" <<'PYCFG'
import sys
from omegaconf import OmegaConf
cfg = OmegaConf.load(sys.argv[1])
print(f"{cfg.experiment.out_root}/{cfg.experiment.name}")
PYCFG
)
# Keep the input cache and held-out-test policy with the run itself. The
# standalone evaluator can then be given only RUN_DIR and reproduce its inputs.
RUN_PROVENANCE="$RUN_DIR/input_provenance.env"
mkdir -p "$RUN_DIR"
printf '# Generated by scripts/train_vlm.sh; do not edit manually.\n' > "$RUN_PROVENANCE"
printf 'VLM_CACHE=%q\n' "$CACHE" >> "$RUN_PROVENANCE"
printf 'VLM_TRAIN_MANIFEST_PROFILE=%q\n' "$MANIFEST_PROFILE" >> "$RUN_PROVENANCE"
printf 'VLM_TEST_MANIFEST_PROFILE=%q\n' "full" >> "$RUN_PROVENANCE"

python -m vlm.train \
  --config "$CONFIG" \
  --manifest "$TRAIN_MANIFEST" \
  --frame_root "$CACHE/overlays/train" \
  --graph_feats "$CACHE/vlmgraph_train.pt" \
  --val_manifest "$VAL_MANIFEST" \
  --val_frame_root "$CACHE/overlays/val" \
  --val_graph_feats "$CACHE/vlmgraph_val.pt" \
  --val_gtmeta "$CACHE/gtmeta_val.pt" \
  "${RESUME_ARGS[@]}"

if [ "$TEST_EVAL" = "1" ]; then
    # train.py snapshots this config before training. Reuse that snapshot so the
    # best adapter is evaluated with exactly its original model/input settings.
    RUN_CONFIG="$RUN_DIR/config_vlm.yaml"
    BEST_CHECKPOINT="$RUN_DIR/train/checkpoints/best"
    if [ ! -f "$RUN_CONFIG" ] || [ ! -d "$BEST_CHECKPOINT" ]; then
        echo "Missing completed run config or best checkpoint: run=$RUN_DIR" >&2
        exit 3
    fi
    if [ -z "$TEST_OUT" ]; then
        TEST_OUT="$RUN_DIR/test"
    fi
    if [ -z "$TEST_NAME" ]; then
        TEST_NAME="$(basename "$RUN_DIR")_${MANIFEST_PROFILE}"
    fi
    WANDB_ARGS=(--wandb_off)
    WANDB_RUN_ID_FILE="$RUN_DIR/wandb_run_id.txt"
    if [ -s "$WANDB_RUN_ID_FILE" ]; then
        WANDB_RUN_ID=$(< "$WANDB_RUN_ID_FILE")
        if [ -n "$WANDB_RUN_ID" ]; then
            WANDB_ARGS=(--wandb_run_id "$WANDB_RUN_ID")
            echo "[vlm] test: resuming W&B run $WANDB_RUN_ID"
        fi
    fi
    echo "[vlm] test: checkpoint=$BEST_CHECKPOINT manifest=$MANIFEST_ROOT/manifest_test.jsonl output=$TEST_OUT"
    python -m vlm.evaluate run --mode vlm --name "$TEST_NAME" --checkpoint "$BEST_CHECKPOINT" --config "$RUN_CONFIG" --manifest "$MANIFEST_ROOT/manifest_test.jsonl" --frame_root "$CACHE/overlays/test" --graph_feats "$CACHE/vlmgraph_test.pt" --gtmeta "$CACHE/gtmeta_test.pt" --output_dir "$TEST_OUT" --batch_size "$TEST_BATCH_SIZE" --num_workers "$TEST_NUM_WORKERS" --device auto "${WANDB_ARGS[@]}"
fi
